CREATE SEQUENCE IF NOT EXISTS policy_number_seq START 1;
CREATE SEQUENCE IF NOT EXISTS claim_number_seq START 1;
CREATE SEQUENCE IF NOT EXISTS contact_code_seq START 1;
CREATE SEQUENCE IF NOT EXISTS account_code_seq START 1;
CREATE SEQUENCE IF NOT EXISTS lead_code_seq START 1;
CREATE SEQUENCE IF NOT EXISTS quotation_code_seq START 1;