CREATE SEQUENCE IF NOT EXISTS policy_number_seq START 1;
CREATE SEQUENCE IF NOT EXISTS claim_number_seq START 1;
CREATE SEQUENCE IF NOT EXISTS contact_number_seq START 1;
CREATE SEQUENCE IF NOT EXISTS account_number_seq START 1;
CREATE SEQUENCE IF NOT EXISTS lead_number_seq START 1;
CREATE SEQUENCE IF NOT EXISTS quotation_number_seq START 1;