apiVersion: v1
kind: Secret
metadata:
  name: jest-api-secrets
  namespace: jest-policy
type: Opaque
stringData:
  DATABASE_URL: "postgresql://user:password@rds.amazonaws.com:5432/jest_crm?schema=public"
  JWT_SECRET: "your-super-secret-jwt-key"
  JWT_REFRESH_SECRET: "your-super-secret-refresh-key"
  REDIS_PASSWORD: "your-redis-password"
