apiVersion: v1
kind: ConfigMap
metadata:
  name: jest-api-config
  namespace: jest-policy
data:
  NODE_ENV: "production"
  PORT: "3000"
  FRONTEND_URL: "https://app.jestpolicy.com"
  REDIS_HOST: "redis-master.jest-policy.svc.cluster.local"
  REDIS_PORT: "6379"
  JWT_EXPIRES_IN: "1h"
  REFRESH_TOKEN_EXPIRES_IN: "7d"
